title:            sean yu
description:      who is sean
url:              https://sean-yu.com
permalink:        pretty
timezone:         America/Los_Angeles
sass:
  sass_dir: assets
  style: :compressed
collections:
  - notes
